apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
  labels:
    app: transaction-service
data:
  application.yml: |
    server:
      port: 10100
      servlet:
        context-path: /transaction-service

    spring:
      application:
        name: TransactionService
      datasource:
        url: jdbc:h2:mem:transaction_server_db
        username: 'sa'
        password: 'password'
      sql:
        init:
          mode: always
          schema-locations:
            - classpath:h2/schema.sql
      messages:
        basename: i18n/messages
    management:
      endpoints:
        web:
          exposure:
            include: health,info
          base-path: /actuator
      endpoint:
        health:
          show-details: when_authorized
          probes:
            enabled: true
      health:
        livenessstate:
          enabled: true
        readinessstate:
          enabled: true